#!/bin/bash

VERSION="1.1.0"
CONFIG_FILE="$HOME/.autonumlock"
CONFIG_FILE_SRC='/usr/share/autonumlock/default_config'

if [[ $1 == "-v" ]]; then

	echo ""
	echo "AutoNumlock v."$VERSION
	echo ""
	echo "(c) 2014, Ondřej Hruška <ondra@ondrovo.com>"
	echo "MIT License"
	echo ""

	exit
fi

if [[ $1 == "-h" ]]; then
	echo ""
	echo "AutoNumlock v."$VERSION
	echo ""
	echo "Script for watching for external keyboard, and enabling numlock when found."
	echo "Intended for use with laptops that lack numeric block on internal keyboard."
	echo ""
	echo "USAGE: $(basename $0) [-h|-v] [<device>] [<interval>]"
	echo "    <device> ...... device ID of your external keyboard (obtained with lsusb)"
	echo "    <interval> .... number of seconds between checking (default: 1)"
	echo "    -h ... help"
	echo "    -v ... version"
	echo ""
	echo "Options override values from config file:"
	echo "  "$CONFIG_FILE
	echo "The config file is created after first successful start (with device id)"
	echo ""
	exit
fi

if [[ -e $CONFIG_FILE ]]; then
	source $CONFIG_FILE

	[ -z "$1" ] || devices=($1)
	[ -z "$2" ] || sleeptime=$2

else
	if [ -z $1 ]; then
		echo "Missing device ID, and no config file found. Use -h for help."
		exit 1
	fi

	devices=($1)
	sleeptime=1

	[ -z "$2" ] || sleeptime=$2

	# create the config file
	devq=$(printf '%q' $1)
	sleepq=$(printf '%q' $sleeptime)
	cat "$CONFIG_FILE_SRC" | sed "s/<DEVICE>/$devq/g" | sed "s/<SLEEP>/$sleepq/g" > "$CONFIG_FILE"

	source $CONFIG_FILE
fi



# prepare the test command

command="lsusb | grep"

for item in ${devices[*]}; do
	command=$command" -e \"$item\""
done




# Show the config

echo ""
echo "Keyboards";
for item in ${devices[*]}
do
    printf " - \"%s\"\n" $item
done
echo ""
echo "Interval: "$sleeptime" s"
echo ""
echo "Test cmd: $command"

echo ""
echo "--- checking started ---"
echo ""

# main loop

last_state=-1
while [ 1 ]; do

	finds=$(eval $command);

	if [[ -z $finds ]]; then

		if [[ $last_state != 0 ]]; then
			echo "External keyboard NOT FOUND, disabling numlock."

			on_disconnect

			last_state=0
		fi

	else

		if [[ $last_state != 1 ]]; then
			echo "External keyboard DETECTED, enabling numlock."

			on_connect

			last_state=1
		fi
	fi

	sleep $sleeptime

done;
