#!/bin/bash
# Maintainer: Ondrej Hruska <ondra@ondrovo.com>

_pkgname="autonumlock"
pkgname="autonumlock"

pkgver="1.1.3"
pkgrel=1

pkgdesc="Script for watching for external keyboard and enabling numlock when connected. Useful for laptops that lack numeric block. Can also be used to alter keyboard layout and run arbitrary scripts, using the config file."
arch=("any")
url="https://github.com/MightyPork/autonumlock"
license=("MIT")

depends=(bash usbutils numlockx)

source=("https://github.com/MightyPork/autonumlock/archive/$pkgver.zip")
provides=($_pkgname)
replaces=($_pkgname "autonumlock-git")

 # may be outdated
md5sums=('92a27b2ea902dd45e45bb27c48252850')

package() {
	# install license

	srcd="${srcdir}/${_pkgname}-${pkgver}/"

	install -Dm 644 $srcd"LICENSE" "${pkgdir}/usr/share/licenses/${_pkgname}/LICENSE"

	mkdir "${pkgdir}/usr/share/${_pkgname}/"

	cp -p $srcd"autonumlock" "${pkgdir}/usr/share/${_pkgname}/"
	cp -p $srcd"default_config" "${pkgdir}/usr/share/${_pkgname}/"

	mkdir -p "${pkgdir}/usr/bin/"
	ln -s "/usr/share/${_pkgname}/autonumlock" "${pkgdir}/usr/bin/autonumlock"
}
